### ISSUE TITLE
Build failure on Ubuntu trusty (clang)

### ISSUE THREAD

**Issue by keithj** [irods/externals#2] opened 2015-12-08 18:25 UTC
````
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
````

Fresh install of trusty (with updates). Build fails on clang:

````
make[3]: Leaving directory `/home/keith/dev/renci/externals.git/clang3.7-0_src/build'
make[2]: Leaving directory `/home/keith/dev/renci/externals.git/clang3.7-0_src/build'
make[1]: Leaving directory `/home/keith/dev/renci/externals.git/clang3.7-0_src/build'
DEBUG:   stderr: In file included from /home/keith/dev/renci/externals.git/clang3.7-0_src/llvm/include/llvm/Target/TargetMachine.h:22:0,
                 from /home/keith/dev/renci/externals.git/clang3.7-0_src/llvm/include/llvm/Target/TargetLowering.h:38,
                 from /home/keith/dev/renci/externals.git/clang3.7-0_src/llvm/lib/Target/AMDGPU/AMDGPUISelLowering.h:19,
                 from /home/keith/dev/renci/externals.git/clang3.7-0_src/llvm/lib/Target/AMDGPU/AMDGPUISelDAGToDAG.cpp:15:
/home/keith/dev/renci/externals.git/clang3.7-0_src/llvm/include/llvm/Target/TargetOptions.h:206:5: internal compiler error: Segmentation fault
     JumpTable::JumpTableType JTType;
     ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
The bug is not reproducible, so it is likely a hardware or OS problem.
make[3]: *** [lib/Target/AMDGPU/CMakeFiles/LLVMAMDGPUCodeGen.dir/AMDGPUISelDAGToDAG.cpp.o] Error 1
make[2]: *** [lib/Target/AMDGPU/CMakeFiles/LLVMAMDGPUCodeGen.dir/all] Error 2
make[1]: *** [all] Error 2
DEBUG: 
ERROR: build failed
````

````
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
````

**Comment by trel** [comment] 2015-12-08 18:34
I've got the same compiler on the same release - and it works here.

If you can reproduce this error (the message suggests it's not necessarily reproducible), then it's not a bug for us - it should go to upstream gcc itself.

I'll leave this open for now until we can get a better handle on it.

**Comment by trel** [comment] 2016-06-05 13:16
This has been compiling cleanly on every run for a while now.

Closing.

**Closed by trel** 2016-06-05 13:16 UTC
